### ISSUE TITLE
Support for armv7l-unknown-linux-gnueabihf (raspberry pi)

### ISSUE THREAD

**Issue by az5112** [phoenixframework/tailwind#75]
Version 1.7.0-rc.2 of phoenix won't start on a raspberry pi host (debian 9.13). After running `mix phx.server` I am greeted with the following:

```
** (Mix) Could not start application tailwind: exited in: Tailwind.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) tailwind is not available for architecture: armv7l-unknown-linux-gnueabihf
            (tailwind 0.1.9) lib/tailwind.ex:284: Tailwind.target/0
            (tailwind 0.1.9) lib/tailwind.ex:157: Tailwind.bin_path/0
            (tailwind 0.1.9) lib/tailwind.ex:174: Tailwind.bin_version/0
            (tailwind 0.1.9) lib/tailwind.ex:100: Tailwind.start/2
            (kernel 8.4) application_master.erl:293: :application_master.start_it_old/4
```

I was wondering if this could be supported? Version 1.6.15 ran without issues.

**Comment by josevalim** [comment]
Support added on 0.1.10.
